server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

spring:
#  profiles:
#    active: @spring.profiles.active@
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.schema}
    username: ${database.username}
    password: ${database.password}
    driverClassName: com.mysql.cj.jdbc.Driver

#  mail:
#    host: ${mail.host}
#    port: ${mail.port}
#    username: ${mail.email}
#    password: ${mail.password}
#    protocol: smtps
#    properties:
#      mail:
#        smtps:
#          auth: ${mail.properties.mail.smtp.auth}
#        starttls:
#          enable: ${mail.properties.mail.smtp.auth.starttls.enable}
#
#
aws:
  region: ${aws.default.region}
  s3:
    buckets:
      account: ${aws.bucket}

##cloud:
##  aws:
##    credentials:
##      access-key: ${aws.access_key}
##      secret-key: ${aws.secret_key}
##
##AWS_ACCESS_KEY_ID: ${aws.access_key}
##AWS_SECRET_ACCESS_KEY: ${aws.secret_key}
##AWS_DEFAULT_REGION: ${aws.region}
