server:
  port: 0
  servlet:
    session:
      cookie:
        secure: true

spring:
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.email}
    password: ${mail.password}
    protocol: smtps
    properties:
      mail:
        smtps:
          auth: ${mail.properties.mail.smtp.auth}
        starttls:
          enable: ${mail.properties.mail.smtp.auth.starttls.enable}

    # Kafka properties
    kafka:
      bootstrap-servers: ${kafka.bootstrap-server.host}:${kafka.bootstrap-server.port}
      template:
        default-topic: mailerTopic
      consumer:
        group-id: mailerId
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#        properties:
#          spring:
#            json:
#              value:
#                default:
#                  type: com.barbenheimer.mailerservice.dto.TicketMailDetailDTO
#              trusted:
#                packages: com.barbenheimer.mailerservice.dto