server:
  port: 0
  servlet:
    session:
      cookie:
        secure: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

spring:
#  profiles:
#    active: @spring.profiles.active@
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.schema}
    username: ${database.username}
    password: ${database.password}
    driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    compatibility-verifier:
        enabled: false
  application:
    name: movie-service

# Kafka properties
  kafka:
    bootstrap-servers: ${spring.kafka.bootstrap-servers}
    template:
      default-topic: mailerTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.barbenheimer.movieservice.event.TicketPurchaseCompleteEvent

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://${discovery.username}:${discovery.password}@${discovery.server.host}:${discovery.server.port}/eureka

## Zipkin
management:
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0


aws:
  region: ${aws.default.region}
  s3:
    buckets:
      account: ${aws.bucket}

stripe:
  api:
    key: ${stripe.api.key}
