version: '3'


networks:
  backend:
  frontend:
  keycloak-and-mysql-network:
    driver: bridge

volumes:
  sql-data:

#
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
      - "start-dev --import-realm"
      - "--spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
#      DB_PORT: "3306"
      KC_DB_URL_DATABASE: keycloak
      JAVA_OPTS_APPEND: -Dkeycloak.migration.export.include-passwords=true
    volumes:
      - ./imports/:/opt/keycloak/data/import:ro
      - ./keycloak/theme/:/opt/keycloak/themes/resource:ro
    ports:
      - "8181:8080"
    depends_on:
      - mysql
    networks:
      - keycloak-and-mysql-network

  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kerri
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - sql-data:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network



#
#


